# Generated by Django 4.2.1 on 2023-05-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('uuid', models.UUIDField(default=0, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('vname', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=20)),
            ],
        ),
    ]
